Filters101/Models/Author.cs
using System.ComponentModel.DataAnnotations;

namespace Filters101.Models
{
    public class Author
    {
        [Required]
        public int Id { get; set; }
        [Required]
        [MaxLength(50)]
        public string FullName { get; set; }
        [MaxLength(30)]
        public string TwitterAlias { get; set; }
        public bool IsEditor { get; set; } // author shouldn't be able to set this
    }
}

Filters101/Controllers/Authors2Controller.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Filters101.Models;
using Microsoft.AspNetCore.Mvc;
using Filters101.Filters;
using Filters101.Interfaces;

namespace Filters101.Controllers
{
    [Route("api/[controller]")]
    [ValidateModel]
    public class Authors2Controller : Controller
    {
        private readonly IAuthorRepository _authorRepository;

        public Authors2Controller(IAuthorRepository authorRepository)
        {
            _authorRepository = authorRepository;
        }

        // GET: api/authors2
        [HttpGet]
        public async Task<ActionResult<List<Author>>> Get()
        {
            return await _authorRepository.ListAsync();
        }

        // GET api/authors2/5
        [HttpGet("{id}")]
        [ValidateAuthorExists]
        public async Task<ActionResult<Author>> Get(int id)
        {
            return Ok(await _authorRepository.GetByIdAsync(id));
        }

        // POST api/authors2
        [HttpPost]
        public async Task<ActionResult<Author>> Post([FromBody]Author author)
        {
            await _authorRepository.AddAsync(author);
            return Ok(author);
        }

        // PUT api/authors2
        [HttpPut]
        [ValidateAuthorExists]
        public async Task<ActionResult<Author>> Put([FromBody]Author author)
        {
            var authorToUpdate = await _authorRepository.GetByIdAsync(author.Id);
            authorToUpdate.FullName = author.FullName;
            authorToUpdate.TwitterAlias = author.TwitterAlias;

            await _authorRepository.UpdateAsync(author);
            return Ok();
        }

        // DELETE api/authors2/5
        [HttpDelete("{id}")]
        [ValidateAuthorExists]
        public async Task<IActionResult> Delete(int id)
        {
            await _authorRepository.DeleteAsync(id);
            return Ok();
        }
    }
}

Filters101/Controllers/AuthorsController.cs
using System.Collections.Generic;
using Filters101.Models;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using Filters101.Interfaces;
using Microsoft.AspNetCore.Mvc.Filters;

namespace Filters101.Controllers
{
    [Route("api/[controller]")]
    public class AuthorsController : Controller
    {
        private readonly IAuthorRepository _authorRepository;

        public AuthorsController(IAuthorRepository authorRepository)
        {
            _authorRepository = authorRepository;
        }

        // GET: api/authors
        [HttpGet]
        public async Task<ActionResult<List<Author>>> Get()
        {
            return await _authorRepository.ListAsync();
        }

        // GET api/authors/5
        [HttpGet("{id}")]
        //[ProducesResponseType(200, Type=typeof(Author))]
        public async Task<IActionResult> Get(int id)
        {
            var author = await _authorRepository.GetByIdAsync(id);
            if (author == null)
            {
                return NotFound(id);
            }
            return Ok(author);
        }

        // POST api/authors
        [HttpPost]
        public async Task<ActionResult<Author>> Post([FromBody]Author author)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            await _authorRepository.AddAsync(author);
            return Ok(author);
        }

        // PUT api/authors
        [HttpPut()]
        public async Task<ActionResult<Author>> Put([FromBody]Author author)
        {
            var authorToUpdate = await _authorRepository.GetByIdAsync(author.Id);
            if (authorToUpdate == null)
            {
                return NotFound(author.Id);
            }
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }
            authorToUpdate.FullName = author.FullName;
            authorToUpdate.TwitterAlias = author.TwitterAlias;
            await _authorRepository.UpdateAsync(authorToUpdate);
            return Ok();
        }

        // DELETE api/values/5
        [HttpDelete("{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            var author = await _authorRepository.GetByIdAsync(id);
            if (author == null)
            {
                return NotFound(id);
            }
            await _authorRepository.DeleteAsync(id);
            return Ok();
        }

        // equivalent to a controller-specific action filter 👇
        public override async Task OnActionExecutionAsync(ActionExecutingContext context, 
            ActionExecutionDelegate next)
        {
            // do work
            await next();

            // do other work
        }

        // GET: api/authors/populate
        [HttpGet("Populate")]
        public async Task<IActionResult> Populate()
        {
            if (!(await _authorRepository.ListAsync()).Any())
            {
                await _authorRepository.AddAsync(new Author()
                {
                    Id = 1,
                    FullName = "Steve Smith",
                    TwitterAlias = "ardalis"
                });
                await _authorRepository.AddAsync(new Author()
                {
                    Id = 2,
                    FullName = "Neil Gaiman",
                    TwitterAlias = "neilhimself"
                });
            }
            return Ok();
        }
    }
}

Filters101/Controllers/HomeController.cs
using System;
using System.Threading;
using Filters101.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Filters101.Controllers
{
    public class HomeController : Controller
    {
        private ILogger _logger;
        public HomeController(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<HomeController>();
        }


        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        [TypeFilter(typeof(DurationActionFilter))]
        public IActionResult RandomTime()
        {
            _logger.LogInformation(nameof(RandomTime));
            Thread.Sleep(new Random().Next(2000));
            return View();
        }


        public IActionResult Error()
        {
            return View();
        }
    }
}

Filters101/Controllers/OrderingController.cs
using Filters101.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.Extensions.Logging;

namespace Filters101.Controllers
{
    [OrderLoggingActionFilter(Name = "Class Level Attribute")]
    [TypeFilter(typeof(OrderLoggingActionFilter), Arguments = new object[] { "Class Attribute" })]
    public class OrderingController : Controller
    {
        private readonly ILogger _logger;
        public OrderingController(ILoggerFactory loggerFactory)
        {
            _logger = loggerFactory.CreateLogger<OrderingController>();
        }

        [OrderLoggingActionFilter(Name = "Method Level Attribute")]
        public IActionResult Index()
        {
            return Content("Ordering Sample.");
        }

        public override void OnActionExecuting(ActionExecutingContext context)
        {
            _logger.LogInformation($"OnActionExecuting for {nameof(OrderingController)}");
            base.OnActionExecuting(context);
        }

        public override void OnActionExecuted(ActionExecutedContext context)
        {
            _logger.LogInformation($"OnActionExecuted for {nameof(OrderingController)}");
            base.OnActionExecuted(context);
        }
    }
}

Filters101/Controllers/RandomNumberController.cs
using System;
using System.Threading;
using Filters101.Filters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace Filters101.Controllers
{
    public class RandomNumberController : Controller
    {
        [ServiceFilter(typeof(RandomNumberProviderFilter))]
        public int GetRandomNumber(int randomNumber)
        {
            return randomNumber;
        }
    }
}

Filters101/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Filters101/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"].</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Filters101/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<h1>Authors API Docs</h1>
<div class="row">
    <ul>
        <li><a href="/swagger">Swagger</a></li>
    </ul>
</div>
<h1>Filters</h1>
<div class="row">
    <ul>
        <li>
            Display Action Duration -
            <a asp-controller="Home" asp-action="RandomTime">Demo</a>
        </li>
        <li>
            Filter Ordering (click then view log output) -
            <a asp-controller="Ordering" asp-action="Index">Demo</a>
        </li>
        <li>
            Random Number Service Filter
            <a asp-controller="RandomNumber" asp-action="GetRandomNumber">Demo</a>
        </li>
    </ul>
</div>

Filters101/Views/Home/RandomTime.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title>Random Time</title>
</head>
<body>
    <div>
        <h1>Random Time</h1>
        This action sleeps for a random period of time up to 2000ms.
    </div>
    <footer>
        Execution Time: @ViewData["actionDuration"] ms
    </footer>
</body>
</html>

Filters101/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Filters101</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-controller="Home" asp-action="Index" class="navbar-brand">Filters101</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - Filters101</p>
            Execution Time: @ViewData["actionDuration"] ms

        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>